Repository farisfaikar/wayry, pull requests merged in 2024-10, with the labels that each got.

#17 docs: CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#19 Update README file
  README.md
Labels: documentation, hacktoberfest-accepted

#20 Add new license file
  LICENSE
Labels: documentation, hacktoberfest-accepted

#21 Issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, hacktoberfest-accepted

#23 Pull Request Template
  PULL_REQUEST_TEMPLATE.md
Labels: documentation, hacktoberfest-accepted

#27 Issue Templates from Markdown to YAML
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: documentation, hacktoberfest-accepted

#30 changes done
  app/dashboard/page.tsx
  components/Loader.tsx
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest-accepted
